services:
  little-big-hero-backend:
    image: vulpery/little-big-hero-backend:latest
    build: .
    container_name: little-big-hero-backend
    command: bash -c "alembic upgrade head && fastapi run app/main.py --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - little-big-hero-db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@little-big-hero-db:5432/${POSTGRES_DB}"
    env_file:
      - .env
  little-big-hero-db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: