"""add quests_id uuid

Revision ID: 3e7cb4a4d8aa
Revises: a1c131cd7162
Create Date: 2024-11-23 17:32:37.685735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7cb4a4d8aa'
down_revision: Union[str, None] = 'a1c131cd7162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
