"""Initial migration

Revision ID: a1c131cd7162
Revises: 
Create Date: 2024-11-23 01:50:01.053831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c131cd7162'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_image', sa.String(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('wallet_address')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    op.create_table('avatars',
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('equipped_items', sa.JSON(), nullable=True),
    sa.Column('cosmetic_details', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['wallet_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('wallet_address')
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('owner_wallet', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('metadata_uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_wallet'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('quests',
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('creator_wallet', sa.String(), nullable=True),
    sa.Column('participant_wallet', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('time_window', sa.JSON(), nullable=True),
    sa.Column('rewards', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('available', 'in_progress', 'completed', 'cancelled', name='queststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_wallet'], ['users.wallet_address'], ),
    sa.ForeignKeyConstraint(['participant_wallet'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('quest_id')
    )
    op.create_index(op.f('ix_quests_quest_id'), 'quests', ['quest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quests_quest_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('avatars')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
