"""add blob to items and latitude and longitude

Revision ID: b032bde1e17f
Revises: 3e7cb4a4d8aa
Create Date: 2024-11-23 18:30:10.973082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b032bde1e17f'
down_revision: Union[str, None] = '3e7cb4a4d8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('quests', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('quests', sa.Column('latitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'latitude')
    op.drop_column('quests', 'longitude')
    op.drop_column('items', 'image_data')
    # ### end Alembic commands ###
